package com.makeitquick.security;

import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.security.SecureRandom; import java.time.*; import java.util.*; import org.springframework.http.*; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;

@RestController @RequestMapping("/api/auth") @CrossOrigin(origins = "*")
public class AuthController {
 private final UserRepository users; private final SessionRepository sessions; private final ResetTokenRepository resets; private final BCryptPasswordEncoder encoder=new BCryptPasswordEncoder(12); private final SecureRandom random=new SecureRandom();
 AuthController(UserRepository u,SessionRepository s,ResetTokenRepository r){users=u;sessions=s;resets=r;}
 @PostMapping("/register") @ResponseStatus(HttpStatus.CREATED) public Map<String,String> register(@Valid @RequestBody Register x){if(users.findByEmailIgnoreCase(x.email()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered"); Role role=Role.valueOf(x.role().toUpperCase()); if(role==Role.ADMIN)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin accounts are created by the operator"); users.save(new UserAccount(x.name(),x.email().toLowerCase(),encoder.encode(x.password()),role));return Map.of("message","Account created");}
 @PostMapping("/login") public Map<String,Object> login(@Valid @RequestBody Login x){UserAccount u=users.findByEmailIgnoreCase(x.email()).filter(a->encoder.matches(x.password(),a.getPasswordHash())&&a.isEnabled()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials"));String token=token();sessions.save(new Session(token,u,Instant.now().plus(Duration.ofHours(24))));return Map.of("token",token,"role",u.getRole(),"name",u.getName());}
 @PostMapping("/forgot-password") public Map<String,String> forgot(@Valid @RequestBody EmailRequest x){users.findByEmailIgnoreCase(x.email()).ifPresent(u->resets.save(new ResetToken(token(),u,Instant.now().plus(Duration.ofMinutes(30)))));return Map.of("message","If the account exists, a reset email has been queued.");}
 @PostMapping("/reset-password") public Map<String,String> reset(@Valid @RequestBody Reset x){ResetToken r=resets.findByToken(x.token()).filter(ResetToken::valid).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid or expired reset token"));r.getUser().setPasswordHash(encoder.encode(x.password()));r.use();users.save(r.getUser());resets.save(r);return Map.of("message","Password updated");}
 private String token(){byte[] b=new byte[48];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
 public record Register(@NotBlank String name,@Email String email,@Size(min=8,max=72) String password,@Pattern(regexp="customer|worker",flags=Pattern.Flag.CASE_INSENSITIVE) String role){} public record Login(@Email String email,@NotBlank String password){} public record EmailRequest(@Email String email){} public record Reset(@NotBlank String token,@Size(min=8,max=72) String password){}
}
