package com.makeitquick.booking;
import com.makeitquick.payment.PaymentStatus;
import com.makeitquick.security.UserAccount; import jakarta.persistence.*; import java.math.BigDecimal; import java.time.Instant;
@Entity @Table(name="bookings")
public class Booking {
 @Id @GeneratedValue(strategy=GenerationType.IDENTITY) private Long id;
 @Version private long version;
 @ManyToOne(optional=false) private UserAccount customer; @ManyToOne private UserAccount worker;
 @Column(nullable=false) private String service; @Column(nullable=false) private String address; @Column(nullable=false) private String scheduledFor; private String pinCode;
 private Integer durationMinutes=60; private String optionLabel; private String promoCode; private Integer discountPaise=0; @Column(length=1000) private String specialInstructions;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private BookingStatus status=BookingStatus.REQUESTED;
 @Enumerated(EnumType.STRING) @Column(nullable=false) private PaymentStatus paymentStatus=PaymentStatus.UNPAID;
 private String paymentMethod; private Integer paymentAmountPaise;
 /** Compatibility column retained from the original admin schema. */
 @Column(name="total_amount", nullable=false, precision=12, scale=2) private BigDecimal totalAmount=BigDecimal.ZERO;
 private Instant paidAt; private boolean instantBooking; private Instant expiresAt;
 private String cancellationReason; private String startOtpHash; private String endOtpHash; private Integer rating; private String ratingComment; @Column(nullable=false,updatable=false) private Instant createdAt=Instant.now();
 protected Booking(){} public Booking(UserAccount c,String s,String a,String t,String pin,Integer duration,String option,String promo,int discount){this(c,s,a,t,pin,duration,option,promo,discount,"");} public Booking(UserAccount c,String s,String a,String t,String pin,Integer duration,String option,String promo,int discount,String instructions){customer=c;service=s;address=a;scheduledFor=t;pinCode=pin;durationMinutes=duration==null?60:duration;optionLabel=option==null?"Standard":option;promoCode=promo;discountPaise=discount;specialInstructions=instructions==null?"":instructions;}
 public Long getId(){return id;} public UserAccount getCustomer(){return customer;} public UserAccount getWorker(){return worker;} public String getService(){return service;} public String getAddress(){return address;} public String getScheduledFor(){return scheduledFor;} public String getPinCode(){return pinCode;} public Integer getDurationMinutes(){return durationMinutes;} public String getOptionLabel(){return optionLabel;} public String getPromoCode(){return promoCode;} public Integer getDiscountPaise(){return discountPaise;} public String getSpecialInstructions(){return specialInstructions==null?"":specialInstructions;} public BookingStatus getStatus(){return status;} public Integer getRating(){return rating;}
 public PaymentStatus getPaymentStatus(){return paymentStatus==null?PaymentStatus.UNPAID:paymentStatus;} public String getPaymentMethod(){return paymentMethod==null?"":paymentMethod;} public Integer getPaymentAmountPaise(){return paymentAmountPaise==null?0:paymentAmountPaise;} public Instant getPaidAt(){return paidAt;} public Instant getCreatedAt(){return createdAt;} public boolean isInstantBooking(){return instantBooking;} public Instant getExpiresAt(){return expiresAt;}
 public void setPaymentAmountPaise(int amountPaise){paymentAmountPaise=amountPaise;totalAmount=BigDecimal.valueOf(amountPaise,2);} public void makeInstant(Instant expiry){instantBooking=true;expiresAt=expiry;status=BookingStatus.SEARCHING;} public void extendInstantSearchUntil(Instant expiry){if(instantBooking)expiresAt=expiry;} public void expire(){status=BookingStatus.EXPIRED;} public void markPaid(String method,int amountPaise){paymentStatus=PaymentStatus.PAID;paymentMethod=method;setPaymentAmountPaise(amountPaise);paidAt=Instant.now();}
 public void assign(UserAccount u){worker=u;status=BookingStatus.ASSIGNED;} public void accept(){status=BookingStatus.ACCEPTED;} public void arrive(){status=BookingStatus.ARRIVED;} public void unassign(){worker=null;status=BookingStatus.REQUESTED;} public void cancel(String r){status=BookingStatus.CANCELLED;cancellationReason=r;} public void reschedule(String s){scheduledFor=s;} public void setStartOtpHash(String h){startOtpHash=h;} public String getStartOtpHash(){return startOtpHash;} public void begin(){status=BookingStatus.IN_PROGRESS;} public void setEndOtpHash(String h){endOtpHash=h;} public String getEndOtpHash(){return endOtpHash;} public void complete(){status=BookingStatus.COMPLETED;} public void rate(int r,String c){rating=r;ratingComment=c;}
 public void setStatus(BookingStatus value){status=value;} public void setWorker(UserAccount w){worker=w;}
 public void enRoute(){status=BookingStatus.ON_THE_WAY;} public String getCancellationReason(){return cancellationReason==null?"":cancellationReason;} public String getRatingComment(){return ratingComment==null?"":ratingComment;}
}
